linter:
  rules:
#    curly_braces_in_flow_control_structures: false
#    prefer_double_quotes: true
#    unawaited_futures: true

# analyzer:
#   language:
#     strict-casts: true
#     strict-inference: true
#     strict-raw-types: true

formatter:
  page_width: 120
