class Currency {
  final String code;
  final String name;
  final String symbol;
  final bool isCrypto;

  const Currency({required this.code, required this.name, required this.symbol, required this.isCrypto});

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Currency && runtimeType == other.runtimeType && code == other.code;

  @override
  int get hashCode => code.hashCode;
}

class Currencies {
  static const usd = Currency(code: 'USD', name: 'US Dollar', symbol: '\$', isCrypto: false);
  static const eur = Currency(code: 'EUR', name: 'Euro', symbol: '€', isCrypto: false);
  static const rub = Currency(code: 'RUB', name: 'Russian Ruble', symbol: '₽', isCrypto: false);
  static const btc = Currency(code: 'BTC', name: 'Bitcoin', symbol: '₿', isCrypto: true);
  static const sol = Currency(code: 'SOL', name: 'Solana', symbol: 'SOL', isCrypto: true);

  static const List<Currency> defaults = [usd, eur, rub, btc, sol];

  static final List<Currency> allFiat = [
    Currency(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', isCrypto: false),
    Currency(code: 'AFN', name: 'Afghan Afghani', symbol: '؋', isCrypto: false),
    Currency(code: 'ALL', name: 'Albanian Lek', symbol: 'L', isCrypto: false),
    Currency(code: 'AMD', name: 'Armenian Dram', symbol: '֏', isCrypto: false),
    Currency(code: 'ANG', name: 'Netherlands Antillian Guilder', symbol: 'ƒ', isCrypto: false),
    Currency(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', isCrypto: false),
    Currency(code: 'ARS', name: 'Argentine Peso', symbol: '\$', isCrypto: false),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: 'A\$', isCrypto: false),
    Currency(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', isCrypto: false),
    Currency(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', isCrypto: false),
    Currency(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', isCrypto: false),
    Currency(code: 'BBD', name: 'Barbadian Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', isCrypto: false),
    Currency(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', isCrypto: false),
    Currency(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', isCrypto: false),
    Currency(code: 'BIF', name: 'Burundian Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'BMD', name: 'Bermudan Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'BND', name: 'Brunei Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', isCrypto: false),
    Currency(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$', isCrypto: false),
    Currency(code: 'BSD', name: 'Bahamian Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', isCrypto: false),
    Currency(code: 'BWP', name: 'Botswanan Pula', symbol: 'P', isCrypto: false),
    Currency(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', isCrypto: false),
    Currency(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$', isCrypto: false),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: 'C\$', isCrypto: false),
    Currency(code: 'CDF', name: 'Congolese Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', isCrypto: false),
    Currency(code: 'CLP', name: 'Chilean Peso', symbol: '\$', isCrypto: false),
    Currency(code: 'CNY', name: 'Chinese Yuan', symbol: '¥', isCrypto: false),
    Currency(code: 'COP', name: 'Colombian Peso', symbol: '\$', isCrypto: false),
    Currency(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', isCrypto: false),
    Currency(code: 'CUP', name: 'Cuban Peso', symbol: '₱', isCrypto: false),
    Currency(code: 'CVE', name: 'Cape Verdean Escudo', symbol: '\$', isCrypto: false),
    Currency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', isCrypto: false),
    Currency(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'DKK', name: 'Danish Krone', symbol: 'kr', isCrypto: false),
    Currency(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$', isCrypto: false),
    Currency(code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', isCrypto: false),
    Currency(code: 'EGP', name: 'Egyptian Pound', symbol: '£', isCrypto: false),
    Currency(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', isCrypto: false),
    Currency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', isCrypto: false),
    eur,
    Currency(code: 'FJD', name: 'Fijian Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', isCrypto: false),
    Currency(code: 'FOK', name: 'Faroese Króna', symbol: 'kr', isCrypto: false),
    Currency(code: 'GBP', name: 'British Pound', symbol: '£', isCrypto: false),
    Currency(code: 'GEL', name: 'Georgian Lari', symbol: '₾', isCrypto: false),
    Currency(code: 'GGP', name: 'Guernsey Pound', symbol: '£', isCrypto: false),
    Currency(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', isCrypto: false),
    Currency(code: 'GIP', name: 'Gibraltar Pound', symbol: '£', isCrypto: false),
    Currency(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', isCrypto: false),
    Currency(code: 'GNF', name: 'Guinean Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', isCrypto: false),
    Currency(code: 'GYD', name: 'Guyanaese Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$', isCrypto: false),
    Currency(code: 'HNL', name: 'Honduran Lempira', symbol: 'L', isCrypto: false),
    Currency(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', isCrypto: false),
    Currency(code: 'HTG', name: 'Haitian Gourde', symbol: 'G', isCrypto: false),
    Currency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', isCrypto: false),
    Currency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', isCrypto: false),
    Currency(code: 'ILS', name: 'Israeli Shekel', symbol: '₪', isCrypto: false),
    Currency(code: 'IMP', name: 'Isle of Man Pound', symbol: '£', isCrypto: false),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹', isCrypto: false),
    Currency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', isCrypto: false),
    Currency(code: 'IRR', name: 'Iranian Rial', symbol: '﷼', isCrypto: false),
    Currency(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', isCrypto: false),
    Currency(code: 'JEP', name: 'Jersey Pound', symbol: '£', isCrypto: false),
    Currency(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$', isCrypto: false),
    Currency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', isCrypto: false),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥', isCrypto: false),
    Currency(code: 'KES', name: 'Kenyan Shilling', symbol: 'Sh', isCrypto: false),
    Currency(code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', isCrypto: false),
    Currency(code: 'KHR', name: 'Cambodian Riel', symbol: '៛', isCrypto: false),
    Currency(code: 'KID', name: 'Kiribati Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'KMF', name: 'Comorian Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'KRW', name: 'South Korean Won', symbol: '₩', isCrypto: false),
    Currency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', isCrypto: false),
    Currency(code: 'KYD', name: 'Cayman Islands Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', isCrypto: false),
    Currency(code: 'LAK', name: 'Laotian Kip', symbol: '₭', isCrypto: false),
    Currency(code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', isCrypto: false),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', isCrypto: false),
    Currency(code: 'LRD', name: 'Liberian Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'LSL', name: 'Lesotho Loti', symbol: 'L', isCrypto: false),
    Currency(code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', isCrypto: false),
    Currency(code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', isCrypto: false),
    Currency(code: 'MDL', name: 'Moldovan Leu', symbol: 'L', isCrypto: false),
    Currency(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', isCrypto: false),
    Currency(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', isCrypto: false),
    Currency(code: 'MMK', name: 'Myanma Kyat', symbol: 'Ks', isCrypto: false),
    Currency(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', isCrypto: false),
    Currency(code: 'MOP', name: 'Macanese Pataca', symbol: 'P', isCrypto: false),
    Currency(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', isCrypto: false),
    Currency(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', isCrypto: false),
    Currency(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: '.ރ', isCrypto: false),
    Currency(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', isCrypto: false),
    Currency(code: 'MXN', name: 'Mexican Peso', symbol: '\$', isCrypto: false),
    Currency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', isCrypto: false),
    Currency(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', isCrypto: false),
    Currency(code: 'NAD', name: 'Namibian Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦', isCrypto: false),
    Currency(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$', isCrypto: false),
    Currency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', isCrypto: false),
    Currency(code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', isCrypto: false),
    Currency(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$', isCrypto: false),
    Currency(code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', isCrypto: false),
    Currency(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', isCrypto: false),
    Currency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', isCrypto: false),
    Currency(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', isCrypto: false),
    Currency(code: 'PHP', name: 'Philippine Peso', symbol: '₱', isCrypto: false),
    Currency(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', isCrypto: false),
    Currency(code: 'PLN', name: 'Polish Zloty', symbol: 'zł', isCrypto: false),
    Currency(code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', isCrypto: false),
    Currency(code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق', isCrypto: false),
    Currency(code: 'RON', name: 'Romanian Leu', symbol: 'lei', isCrypto: false),
    Currency(code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', isCrypto: false),
    rub,
    Currency(code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', isCrypto: false),
    Currency(code: 'SBD', name: 'Solomon Islands Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', isCrypto: false),
    Currency(code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', isCrypto: false),
    Currency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr', isCrypto: false),
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$', isCrypto: false),
    Currency(code: 'SHP', name: 'Saint Helena Pound', symbol: '£', isCrypto: false),
    Currency(code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', isCrypto: false),
    Currency(code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', isCrypto: false),
    Currency(code: 'SRD', name: 'Surinamese Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'SSP', name: 'South Sudanese Pound', symbol: '£', isCrypto: false),
    Currency(code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', isCrypto: false),
    Currency(code: 'SYP', name: 'Syrian Pound', symbol: '£', isCrypto: false),
    Currency(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', isCrypto: false),
    Currency(code: 'THB', name: 'Thai Baht', symbol: '฿', isCrypto: false),
    Currency(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', isCrypto: false),
    Currency(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', isCrypto: false),
    Currency(code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', isCrypto: false),
    Currency(code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T\$', isCrypto: false),
    Currency(code: 'TRY', name: 'Turkish Lira', symbol: '₺', isCrypto: false),
    Currency(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT\$', isCrypto: false),
    Currency(code: 'TVD', name: 'Tuvaluan Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$', isCrypto: false),
    Currency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh', isCrypto: false),
    Currency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', isCrypto: false),
    Currency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'Sh', isCrypto: false),
    usd,
    Currency(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U', isCrypto: false),
    Currency(code: 'UZS', name: 'Uzbekistan Som', symbol: 'so\'m', isCrypto: false),
    Currency(code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.', isCrypto: false),
    Currency(code: 'VND', name: 'Vietnamese Dong', symbol: '₫', isCrypto: false),
    Currency(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', isCrypto: false),
    Currency(code: 'WST', name: 'Samoan Tala', symbol: 'T', isCrypto: false),
    Currency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'XCD', name: 'East Caribbean Dollar', symbol: '\$', isCrypto: false),
    Currency(code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR', isCrypto: false),
    Currency(code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'XPF', name: 'CFP Franc', symbol: 'Fr', isCrypto: false),
    Currency(code: 'YER', name: 'Yemeni Rial', symbol: '﷼', isCrypto: false),
    Currency(code: 'ZAR', name: 'South African Rand', symbol: 'R', isCrypto: false),
    Currency(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', isCrypto: false),
    Currency(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '\$', isCrypto: false),
  ];

  static final List<Currency> allCrypto = [
    btc,
    Currency(code: 'ETH', name: 'Ethereum', symbol: 'ETH', isCrypto: true),
    Currency(code: 'USDT', name: 'Tether', symbol: 'USDT', isCrypto: true),
    Currency(code: 'BNB', name: 'Binance Coin', symbol: 'BNB', isCrypto: true),
    sol,
    Currency(code: 'XRP', name: 'Ripple', symbol: 'XRP', isCrypto: true),
    Currency(code: 'USDC', name: 'USD Coin', symbol: 'USDC', isCrypto: true),
    Currency(code: 'ADA', name: 'Cardano', symbol: 'ADA', isCrypto: true),
    Currency(code: 'DOGE', name: 'Dogecoin', symbol: 'DOGE', isCrypto: true),
    Currency(code: 'TRX', name: 'TRON', symbol: 'TRX', isCrypto: true),
    Currency(code: 'TON', name: 'Toncoin', symbol: 'TON', isCrypto: true),
    Currency(code: 'LINK', name: 'Chainlink', symbol: 'LINK', isCrypto: true),
    Currency(code: 'AVAX', name: 'Avalanche', symbol: 'AVAX', isCrypto: true),
    Currency(code: 'SHIB', name: 'Shiba Inu', symbol: 'SHIB', isCrypto: true),
    Currency(code: 'DOT', name: 'Polkadot', symbol: 'DOT', isCrypto: true),
    Currency(code: 'BCH', name: 'Bitcoin Cash', symbol: 'BCH', isCrypto: true),
    Currency(code: 'UNI', name: 'Uniswap', symbol: 'UNI', isCrypto: true),
    Currency(code: 'LTC', name: 'Litecoin', symbol: 'LTC', isCrypto: true),
    Currency(code: 'NEAR', name: 'NEAR Protocol', symbol: 'NEAR', isCrypto: true),
    Currency(code: 'MATIC', name: 'Polygon', symbol: 'MATIC', isCrypto: true),
    Currency(code: 'DAI', name: 'Dai', symbol: 'DAI', isCrypto: true),
    Currency(code: 'LEO', name: 'UNUS SED LEO', symbol: 'LEO', isCrypto: true),
    Currency(code: 'ICP', name: 'Internet Computer', symbol: 'ICP', isCrypto: true),
    Currency(code: 'ETC', name: 'Ethereum Classic', symbol: 'ETC', isCrypto: true),
    Currency(code: 'APT', name: 'Aptos', symbol: 'APT', isCrypto: true),
    Currency(code: 'STX', name: 'Stacks', symbol: 'STX', isCrypto: true),
    Currency(code: 'XLM', name: 'Stellar', symbol: 'XLM', isCrypto: true),
    Currency(code: 'ATOM', name: 'Cosmos', symbol: 'ATOM', isCrypto: true),
    Currency(code: 'OKB', name: 'OKB', symbol: 'OKB', isCrypto: true),
    Currency(code: 'FIL', name: 'Filecoin', symbol: 'FIL', isCrypto: true),
    Currency(code: 'HBAR', name: 'Hedera', symbol: 'HBAR', isCrypto: true),
    Currency(code: 'ARB', name: 'Arbitrum', symbol: 'ARB', isCrypto: true),
    Currency(code: 'VET', name: 'VeChain', symbol: 'VET', isCrypto: true),
    Currency(code: 'MNT', name: 'Mantle', symbol: 'MNT', isCrypto: true),
    Currency(code: 'INJ', name: 'Injective', symbol: 'INJ', isCrypto: true),
    Currency(code: 'OP', name: 'Optimism', symbol: 'OP', isCrypto: true),
    Currency(code: 'MKR', name: 'Maker', symbol: 'MKR', isCrypto: true),
    Currency(code: 'RUNE', name: 'THORChain', symbol: 'RUNE', isCrypto: true),
    Currency(code: 'GRT', name: 'The Graph', symbol: 'GRT', isCrypto: true),
    Currency(code: 'ALGO', name: 'Algorand', symbol: 'ALGO', isCrypto: true),
    Currency(code: 'AAVE', name: 'Aave', symbol: 'AAVE', isCrypto: true),
    Currency(code: 'THETA', name: 'Theta Network', symbol: 'THETA', isCrypto: true),
    Currency(code: 'FLOW', name: 'Flow', symbol: 'FLOW', isCrypto: true),
    Currency(code: 'XTZ', name: 'Tezos', symbol: 'XTZ', isCrypto: true),
    Currency(code: 'SAND', name: 'The Sandbox', symbol: 'SAND', isCrypto: true),
    Currency(code: 'EOS', name: 'EOS', symbol: 'EOS', isCrypto: true),
    Currency(code: 'AXS', name: 'Axie Infinity', symbol: 'AXS', isCrypto: true),
    Currency(code: 'MANA', name: 'Decentraland', symbol: 'MANA', isCrypto: true),
    Currency(code: 'FTM', name: 'Fantom', symbol: 'FTM', isCrypto: true),
    Currency(code: 'EGLD', name: 'MultiversX', symbol: 'EGLD', isCrypto: true),
    Currency(code: 'XMR', name: 'Monero', symbol: 'XMR', isCrypto: true),
    Currency(code: 'KAVA', name: 'Kava', symbol: 'KAVA', isCrypto: true),
    Currency(code: 'CHZ', name: 'Chiliz', symbol: 'CHZ', isCrypto: true),
    Currency(code: 'ZEC', name: 'Zcash', symbol: 'ZEC', isCrypto: true),
    Currency(code: 'MINA', name: 'Mina', symbol: 'MINA', isCrypto: true),
    Currency(code: '1INCH', name: '1inch Network', symbol: '1INCH', isCrypto: true),
    Currency(code: 'ENJ', name: 'Enjin Coin', symbol: 'ENJ', isCrypto: true),
    Currency(code: 'BAT', name: 'Basic Attention Token', symbol: 'BAT', isCrypto: true),
    Currency(code: 'ZIL', name: 'Zilliqa', symbol: 'ZIL', isCrypto: true),
    Currency(code: 'DASH', name: 'Dash', symbol: 'DASH', isCrypto: true),
    Currency(code: 'COMP', name: 'Compound', symbol: 'COMP', isCrypto: true),
    Currency(code: 'CRV', name: 'Curve DAO Token', symbol: 'CRV', isCrypto: true),
    Currency(code: 'YFI', name: 'yearn.finance', symbol: 'YFI', isCrypto: true),
    Currency(code: 'SNX', name: 'Synthetix', symbol: 'SNX', isCrypto: true),
    Currency(code: 'SUSHI', name: 'SushiSwap', symbol: 'SUSHI', isCrypto: true),
    Currency(code: 'LDO', name: 'Lido DAO', symbol: 'LDO', isCrypto: true),
    Currency(code: 'GMT', name: 'STEPN', symbol: 'GMT', isCrypto: true),
    Currency(code: 'CAKE', name: 'PancakeSwap', symbol: 'CAKE', isCrypto: true),
    Currency(code: 'APE', name: 'ApeCoin', symbol: 'APE', isCrypto: true),
    Currency(code: 'CFX', name: 'Conflux', symbol: 'CFX', isCrypto: true),
    Currency(code: 'IMX', name: 'Immutable X', symbol: 'IMX', isCrypto: true),
    Currency(code: 'LRC', name: 'Loopring', symbol: 'LRC', isCrypto: true),
    Currency(code: 'KCS', name: 'KuCoin Token', symbol: 'KCS', isCrypto: true),
    Currency(code: 'GALA', name: 'Gala', symbol: 'GALA', isCrypto: true),
    Currency(code: 'FXS', name: 'Frax Share', symbol: 'FXS', isCrypto: true),
    Currency(code: 'GLMR', name: 'Moonbeam', symbol: 'GLMR', isCrypto: true),
    Currency(code: 'MASK', name: 'Mask Network', symbol: 'MASK', isCrypto: true),
    Currency(code: 'AR', name: 'Arweave', symbol: 'AR', isCrypto: true),
    Currency(code: 'CELO', name: 'Celo', symbol: 'CELO', isCrypto: true),
    Currency(code: 'HNT', name: 'Helium', symbol: 'HNT', isCrypto: true),
    Currency(code: 'ROSE', name: 'Oasis Network', symbol: 'ROSE', isCrypto: true),
    Currency(code: 'ONE', name: 'Harmony', symbol: 'ONE', isCrypto: true),
    Currency(code: 'KLAY', name: 'Klaytn', symbol: 'KLAY', isCrypto: true),
    Currency(code: 'QTUM', name: 'Qtum', symbol: 'QTUM', isCrypto: true),
    Currency(code: 'ZRX', name: '0x', symbol: 'ZRX', isCrypto: true),
    Currency(code: 'WAVES', name: 'Waves', symbol: 'WAVES', isCrypto: true),
    Currency(code: 'JST', name: 'JUST', symbol: 'JST', isCrypto: true),
    Currency(code: 'ICX', name: 'ICON', symbol: 'ICX', isCrypto: true),
    Currency(code: 'OMG', name: 'OMG Network', symbol: 'OMG', isCrypto: true),
    Currency(code: 'ANKR', name: 'Ankr', symbol: 'ANKR', isCrypto: true),
    Currency(code: 'SC', name: 'Siacoin', symbol: 'SC', isCrypto: true),
    Currency(code: 'SKL', name: 'SKALE Network', symbol: 'SKL', isCrypto: true),
    Currency(code: 'IOTX', name: 'IoTeX', symbol: 'IOTX', isCrypto: true),
    Currency(code: 'RVN', name: 'Ravencoin', symbol: 'RVN', isCrypto: true),
    Currency(code: 'STORJ', name: 'Storj', symbol: 'STORJ', isCrypto: true),
  ];

  static List<Currency> get all => [...allFiat, ...allCrypto];
}
